# Generated by Django 3.1.5 on 2021-01-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0048_auto_20200429_0736"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalrequest",
            options={"get_latest_by": "modified"},
        ),
    ]
