# Generated by Django 3.1.5 on 2021-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0049_auto_20210125_2056"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="activity_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Charity"),
                    (2, "Animal Protection"),
                    (3, "Religious"),
                    (4, "Youth and children"),
                    (5, "Nature Protection"),
                    (6, "Education"),
                    (7, "Art, Culture and Traditions"),
                    (8, "Health"),
                    (9, "Human Rights"),
                    (10, "Volunteers"),
                ],
                null=True,
                verbose_name="Activity Type",
            ),
        ),
    ]
