name: ajut-dev

on:
  push:
    branches: [ master ]

jobs:
  deploy-ajut-dev:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SSH_HOST }}
        username: ${{ secrets.DEPLOY_SSH_USERNAME }}
        password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
        port: ${{ secrets.DEPLOY_SSH_PORT }}
        script: ansible-playbook -i 'localhost,' -c local /home/deploy/ajut-infra/provision/ansible/playbooks/deploy.yml --extra-vars="name='ajut-dev'"
